files:
  - source: translations/translation_de.xml
    translation: /**/%original_path%/translation_%two_letters_code%.xml
    content_segmentation: 0
    translatable_elements:
      - '/l10n/texts/text[@text]'
      - /l10n/translationContributors
